---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc-app-deployment
spec:
  selector:
    matchLabels:
      app: rpc-app
  replicas: 1
  template:
    metadata:
      labels:
        app: rpc-app
    spec:
      containers:
        - name: rpc-app-cont
          image: supergiantkir/prometheus-test-app
          ports:
            - name: web
              containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: rpc-app-service
  labels:
    app: rpc-app
spec:
  ports:
    - name: web
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: rpc-app
